commerce_payment.commerce_payment_gateway.plugin.midtrans:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    server_key:
      type: string
      label: 'Server key'
    client_key:
      type: string
      label: 'Client key'
    enable_3ds:
      type: boolean
      label: 'Enable 3DS'
    enable_redirect:
      type: boolean
      label: 'Enable Redirect'
    enable_savecard:
      type: boolean
      label: 'Enable Save Card'
    custom_expiry:
      type: string
      label: 'Custom Expiry'
    custom_field:
      type: string
      label: 'Custom Field'

commerce_payment.commerce_payment_gateway.plugin.midtrans_installment:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    server_key:
      type: string
      label: 'Server key'
    client_key:
      type: string
      label: 'Client key'
    enable_3ds:
      type: boolean
      label: 'Enable 3DS'
    enable_redirect:
      type: boolean
      label: 'Enable Redirect'
    enable_savecard:
      type: boolean
      label: 'Enable Save Card'
    min_amount:
      type: string
      label: 'Minimal Amount'
    custom_field:
      type: string
      label: 'Custom Field'

commerce_payment.commerce_payment_gateway.plugin.midtrans_installmentoff:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    server_key:
      type: string
      label: 'Server key'
    client_key:
      type: string
      label: 'Client key'
    enable_3ds:
      type: boolean
      label: 'Enable 3DS'
    enable_redirect:
      type: boolean
      label: 'Enable Redirect'
    enable_savecard:
      type: boolean
      label: 'Enable Save Card'
    min_amount:
      type: string
      label: 'Minimal Amount'
    bin_number:
      type: string
      label: 'CC Bins'  
    custom_field:
      type: string
      label: 'Custom Field'
      
commerce_payment.commerce_payment_gateway.plugin.midtrans_promo:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    server_key:
      type: string
      label: 'Server key'
    client_key:
      type: string
      label: 'Client key'
    enable_3ds:
      type: boolean
      label: 'Enable 3DS'
    enable_redirect:
      type: boolean
      label: 'Enable Redirect'
    enable_savecard:
      type: boolean
      label: 'Enable Save Card'
    method_enabled:
      type: string
      label: 'Enable Payment'   
    min_amount:
      type: string
      label: 'Minimal Amount'
    bin_number:
      type: string
      label: 'CC Bins'
    discount_type:
      type: string
      label: 'Discount Type'
    discount_amount:
      type: number
      label: 'Discount Amount'
    max_discount:
      type: number
      label: 'Maximun Discount'  
    custom_expiry:
      type: string
      label: 'Custom Expiry'       
    custom_field:
      type: string
      label: 'Custom Field'